repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
      - id: isort
        exclude: migrations/
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        exclude: migrations/
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        exclude: migrations/
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ""
    hooks:
      - id: prettier
        exclude_types: [html, json]
