# Generated by Django 3.1.3 on 2020-12-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, default='wjFOOO', max_length=30, verbose_name='user id'),
        ),
    ]
