# Generated by Django 3.1.3 on 2020-12-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201205_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='user id'),
        ),
    ]
