# Generated by Django 3.1.3 on 2020-12-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201205_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='None', max_length=30, unique=True, verbose_name='user id'),
            preserve_default=False,
        ),
    ]
