# Generated by Django 3.1.3 on 2020-12-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201205_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='user id'),
        ),
    ]
