# Generated by Django 3.1.3 on 2020-12-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name_plural': 'genre'},
        ),
    ]
