# Generated by Django 3.1.3 on 2021-01-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='place_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
