# Generated by Django 3.1.3 on 2021-01-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0002_auto_20210104_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
