# Generated by Django 3.1.3 on 2020-12-09 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0002_auto_20201209_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='requested_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
