# Generated by Django 3.1.3 on 2020-12-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0002_auto_20201204_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (2, '女'), (3, 'その他')], default=0, null=True),
        ),
    ]
