# Generated by Django 3.1.3 on 2021-01-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0004_auto_20210108_1047'),
        ('asovi_app', '0002_auto_20210104_1826'),
    ]

    operations = [
    ]
