# Generated by Django 3.1.3 on 2020-12-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0004_auto_20201217_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (2, '女'), (3, 'その他')], default=0, null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='static/asovi_app/img/', verbose_name='アイコン'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interested_genre',
            field=models.ManyToManyField(to='asovi_app.Genre', verbose_name='興味のあるジャンル'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='紹介文'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=50, verbose_name='ユーザーネーム'),
        ),
    ]
