# Generated by Django 3.1.3 on 2021-01-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0005_merge_20210111_1621'),
        ('asovi_app', '0005_merge_20210117_1814'),
    ]

    operations = [
    ]
