# Generated by Django 3.1.3 on 2020-12-19 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0005_auto_20201217_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_genre', to='asovi_app.genre'),
        ),
    ]
