# Generated by Django 3.1.3 on 2020-12-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0006_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save',
            old_name='article',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='save',
            old_name='user',
            new_name='person',
        ),
    ]
