# Generated by Django 3.1.3 on 2020-12-21 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0006_post_genre'),
        ('asovi_app', '0004_post_posted_by'),
    ]

    operations = [
    ]
