# Generated by Django 3.1.3 on 2021-01-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0006_merge_20210131_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('place_name', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='place_name',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='post',
            name='genre',
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='post_genre', to='asovi_app.Genre'),
        ),
        migrations.AlterField(
            model_name='post',
            name='place_id',
            field=models.TextField(null=True),
        ),
    ]
