# Generated by Django 3.1.3 on 2020-12-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0006_post_genre'),
        ('asovi_app', '0004_post_posted_by'),
        ('asovi_app', '0007_auto_20201220_1850'),
    ]

    operations = [
    ]
