# Generated by Django 3.1.3 on 2021-01-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0006_merge_20210130_1705'),
        ('asovi_app', '0007_auto_20210131_1714'),
        ('asovi_app', '0006_merge_20210131_0027'),
    ]

    operations = [
    ]
