# Generated by Django 3.1.3 on 2020-12-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0008_merge_20201224_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
