# Generated by Django 3.1.3 on 2021-02-01 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0008_merge_20210131_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='genre',
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_genre', to='asovi_app.genre'),
        ),
        migrations.AlterField(
            model_name='post',
            name='place_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
