# Generated by Django 3.1.3 on 2020-12-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0008_auto_20201220_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='genre',
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.ManyToManyField(to='asovi_app.Genre'),
        ),
    ]
