# Generated by Django 3.1.3 on 2020-12-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0009_remove_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='place_id',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
    ]
