# Generated by Django 3.1.3 on 2021-02-02 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0009_auto_20210201_2153'),
        ('asovi_app', '0008_merge_20210201_1851'),
    ]

    operations = [
    ]
