# Generated by Django 3.1.3 on 2020-12-27 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0010_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
