# Generated by Django 3.1.3 on 2021-02-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0010_merge_20210202_2205'),
        ('asovi_app', '0010_merge_20210202_1035'),
    ]

    operations = [
    ]
