# Generated by Django 3.1.3 on 2020-12-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0011_auto_20201231_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='save',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
