# Generated by Django 3.1.3 on 2021-02-03 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0011_merge_20210202_2236'),
        ('asovi_app', '0011_merge_20210202_2211'),
    ]

    operations = [
    ]
