# Generated by Django 3.1.3 on 2021-01-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0012_post_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='genre',
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_genre', to='asovi_app.Genre'),
        ),
    ]
