# Generated by Django 3.1.3 on 2020-12-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0012_auto_20201231_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='requested_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
