# Generated by Django 3.1.3 on 2021-01-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0015_auto_20210101_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='friend',
            field=models.BooleanField(null=True, verbose_name='通知設定:フレンドリクエスト'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='good',
            field=models.BooleanField(null=True, verbose_name='通知設定:いいね'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='reply',
            field=models.BooleanField(null=True, verbose_name='通知設定:返信'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='save',
            field=models.BooleanField(null=True, verbose_name='通知設定:保存'),
        ),
    ]
