# Generated by Django 3.1.3 on 2021-01-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0016_auto_20210101_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationsetting',
            options={},
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='friend',
            field=models.IntegerField(default=0, verbose_name='通知設定:フレンドリクエスト'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='good',
            field=models.IntegerField(default=0, verbose_name='通知設定:いいね'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='reply',
            field=models.IntegerField(default=0, verbose_name='通知設定:返信'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='save',
            field=models.IntegerField(default=0, verbose_name='通知設定:保存'),
        ),
    ]
