# Generated by Django 3.1.3 on 2021-01-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0020_auto_20210102_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='good',
            field=models.BooleanField(default=True, verbose_name='通知設定:いいね'),
        ),
    ]
