# Generated by Django 3.1.3 on 2021-01-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0021_auto_20210102_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationsetting',
            options={'verbose_name_plural': '通知設定'},
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='friend',
            field=models.IntegerField(default=True, verbose_name='通知設定:フレンドリクエスト'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='reply',
            field=models.IntegerField(default=True, verbose_name='通知設定:返信'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='save',
            field=models.BooleanField(default=True, verbose_name='通知設定:保存'),
        ),
    ]
