# Generated by Django 3.1.3 on 2021-01-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0023_auto_20210102_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsetting',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='notificationsetting',
            name='reply',
        ),
    ]
