# Generated by Django 3.1.3 on 2021-01-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0025_remove_notificationsetting_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='reply',
            field=models.BooleanField(default=True, verbose_name='通知設定:返信'),
        ),
    ]
