# Generated by Django 3.1.3 on 2021-01-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0028_notificationsetting_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationsetting',
            old_name='save',
            new_name='saved',
        ),
    ]
