# Generated by Django 3.1.3 on 2021-01-02 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0030_auto_20210102_0023'),
        ('asovi_app', '0011_auto_20201227_1733'),
    ]

    operations = [
    ]
