# Generated by Django 3.1.3 on 2021-01-04 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asovi_app', '0010_post_place_id'),
        ('asovi_app', '0031_merge_20210102_1135'),
    ]

    operations = [
    ]
